./tester.sh resources/champs/42.s
./tester.sh resources/champs/asombra.s
./tester.sh resources/champs/barriere.s
./tester.sh resources/champs/car.s
./tester.sh resources/champs/ex.s
./tester.sh resources/champs/ex2.s
./tester.sh resources/champs/gagnant.s
./tester.sh resources/champs/jumper.s
./tester.sh resources/champs/lde.s
./tester.sh resources/champs/leeloo.s
./tester.sh resources/champs/mat.s
./tester.sh resources/champs/maxidef.s
./tester.sh resources/champs/mortel.s
./tester.sh resources/champs/octobre_rouge_v4.2.s
./tester.sh resources/champs/slider2.s
./tester.sh resources/champs/survivor.s
./tester.sh resources/champs/toto.s
rm *.cor
rm resources/champs/*.cor